CREATE TABLE  "COMPANY_MAILER_USER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	"GENDER" VARCHAR2(4000), 
	"DOB" DATE, 
	"ADDRESSLINE" VARCHAR2(4000), 
	"CITY" VARCHAR2(4000), 
	"STATE" VARCHAR2(4000), 
	"COUNTRY" VARCHAR2(4000), 
	"CONTACT" VARCHAR2(4000), 
	"REGISTEREDDATE" DATE, 
	"AUTHORIZED" VARCHAR2(4000), 
	 CONSTRAINT "COMPANY_MAILER_USER_PK" PRIMARY KEY ("ID") ENABLE
   )
/

CREATE TABLE  "COMPANY_MAILER_MESSAGE" 
   (	"ID" NUMBER, 
	"SENDER" VARCHAR2(4000), 
	"RECEIVER" VARCHAR2(4000), 
	"SUBJECT" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"TRASH" VARCHAR2(4000), 
	"MESSAGEDATE" DATE, 
	 CONSTRAINT "COMPANY_MAILER_MESSAGE_PK" PRIMARY KEY ("ID") ENABLE
   )
/

create sequence MAILER_SEQ start with 1001 increment by 1
/

create sequence MAILER_MESSAGE start with 1001 increment by 1
/